python_library(
    name = 'sites.myred',
    sources = ['myred.py'],
    dependencies = [
        'src/splinterbot:splinterbot',
    ]
)

python_library(
    name = 'sites.wells_fargo',
    sources = ['wells_fargo.py'],
    dependencies = [
        'src/splinterbot:splinterbot'
    ]
)
