#!/usr/bin/env bash

cd src
zip -r ../WFTransactionGrabber *.py
cd ..

echo '#!/usr/bin/env python' | cat - WFTransactionGrabber.zip > WFTransactionGrabber
chmod +x WFtransactionGrabber
rm WFTransactionGrabber.zip
