#!/usr/bin/env bash

pip install -r requirements.txt

pants :

# Copy pex's to bin/ and remove extension
mkdir -p bin/

for file in dist/*.pex
do
    filename="${file/dist/}"
    cp "$file" "bin/${filename/.pex/}"
done
