python_library(
    name = 'gmail',
    sources = ['gmail.py']
)

python_library(
    name = 'splinterbot',
    dependencies = [
        'src/splinterbot:browsers',
        'src/splinterbot:utils'
    ]
)
