python_library(
    name = 'browsers',
    sources = ['browsers.py'],
    dependencies = [
        '//:splinter',
        ':utils'
    ]
)

python_library(
    name = 'utils',
    sources = ['utils.py']
)

python_library(
    name = 'gmail',
    sources = ['gmail.py']
)
