python_library(
    name = 'browsers',
    sources = ['browsers.py'],
    dependencies = [
        'src:driver_utils',
        '//:splinter'
    ]
)

python_library(
    name = 'driver_utils',
    sources = ['driver_utils.py']
)
